name: Pull Request Validation

on:
  pull_request:
    branches: [ main, develop ]
    paths-ignore:
      - 'docs/**'
      - '**.md'
  push:
    branches: [ main, develop ]
    paths-ignore:
      - 'docs/**'
      - '**.md'

# cancel in-progress jobs or runs for this workflow for the same pr or branch
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  # Improve performance with parallel builds
  MAVEN_OPTS: -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false -Dmaven.wagon.http.retryHandler.class=standard -Dmaven.wagon.http.retryHandler.count=2

jobs:
  lint:
    name: Code Quality & Formatting
    runs-on: ubuntu-latest
    timeout-minutes: 15
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
        
    - name: Check code formatting and license headers
      run: make lint

  build:
    name: Build & Unit Tests
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      matrix:
        java-version: ['17', '21', '24']
        
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK ${{ matrix.java-version }}
      uses: actions/setup-java@v4
      with:
        java-version: ${{ matrix.java-version }}
        distribution: 'temurin'
        cache: maven
        
    - name: Compile code and install
      run: make install
      
    - name: Run unit tests
      run: make test-unit
      
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results-java-${{ matrix.java-version }}
        path: src/*/target/surefire-reports/

    - name: Remove SNAPSHOT jars from repository
      run: |
        find ~/.m2/repository -name "*SNAPSHOT*" -type d | xargs rm -rf {}

  integration-tests:
    name: Integration Tests
    runs-on: ubuntu-latest
    timeout-minutes: 25
    needs: [lint, build]
    
    strategy:
      matrix:
        java-version: ['17', '21', '24']
        test-group: ['reader']
        
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK ${{ matrix.java-version }}
      uses: actions/setup-java@v4
      with:
        java-version: ${{ matrix.java-version }}
        distribution: 'temurin'
        cache: maven
        
    - name: Install dependencies
      run: ./mvnw clean install -pl src/tileverse-pmtiles-reader -am -DskipTests -ntp -U
      
    - name: Run integration tests - ${{ matrix.test-group }} (Java ${{ matrix.java-version }})
      run: make test-${{ matrix.test-group }}-it
      
    - name: Upload integration test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: integration-test-results-${{ matrix.test-group }}-java-${{ matrix.java-version }}
        path: src/*/target/failsafe-reports/

    - name: Remove SNAPSHOT jars from repository
      run: |
        find ~/.m2/repository -name "*SNAPSHOT*" -type d | xargs rm -rf {}

  # Summary job that depends on all others
  pr-validation-complete:
    name: PR Validation Complete
    runs-on: ubuntu-latest
    needs: [lint, build, integration-tests]
    if: always()
    
    steps:
    - name: Check all jobs status
      run: |
        echo "Lint: ${{ needs.lint.result }}"
        echo "Build: ${{ needs.build.result }}"
        echo "Integration Tests: ${{ needs.integration-tests.result }}"
        
        if [[ "${{ needs.lint.result }}" != "success" || 
              "${{ needs.build.result }}" != "success" || 
              "${{ needs.integration-tests.result }}" != "success" ]]; then
          echo "❌ PR validation failed"
          exit 1
        else
          echo "✅ PR validation successful"
        fi
