name: Publish Snapshot

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  publish-snapshot:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
        
    - name: Import GPG key
      uses: crazy-max/ghaction-import-gpg@v6
      with:
        gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
        passphrase: ${{ secrets.GPG_PASSPHRASE }}
        
    - name: Configure Maven settings
      uses: s4u/maven-settings-action@v3.1.0
      with:
        servers: |
          [{
            "id": "central",
            "username": "${{ secrets.CENTRAL_USERNAME }}",
            "password": "${{ secrets.CENTRAL_TOKEN }}"
          }]
          
    - name: Build and test (manual trigger only)
      if: ${{ github.event_name == 'workflow_dispatch' }}
      run: ./mvnw clean verify -U
      
    - name: Publish snapshot
      if: ${{ !contains(github.event.head_commit.message, '[skip-publish]') }}
      run: ./mvnw deploy -DskipTests -Dgpg.skip=false
      env:
        GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}