name: Publish Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g., 1.0.0)'
        required: true
        type: string

jobs:
  publish-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
        
    - name: Import GPG key
      uses: crazy-max/ghaction-import-gpg@v6
      with:
        gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
        passphrase: ${{ secrets.GPG_PASSPHRASE }}
        
    - name: Configure Maven settings
      uses: s4u/maven-settings-action@v3.1.0
      with:
        servers: |
          [{
            "id": "central",
            "username": "${{ secrets.CENTRAL_USERNAME }}",
            "password": "${{ secrets.CENTRAL_TOKEN }}"
          }]
          
    - name: Set release version
      run: |
        if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
          VERSION="${{ github.event.inputs.version }}"
        else
          VERSION="${GITHUB_REF#refs/tags/v}"
        fi
        echo "RELEASE_VERSION=$VERSION" >> $GITHUB_ENV
        echo "Release version: $VERSION"
        
    - name: Build and test
      run: ./mvnw clean verify -Drevision=${{ env.RELEASE_VERSION }} -U
      
    - name: Publish release
      if: ${{ !contains(github.event.head_commit.message, '[skip-publish]') }}
      run: ./mvnw deploy -DskipTests -Drevision=${{ env.RELEASE_VERSION }} -Dgpg.skip=false
      env:
        GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        
    - name: Create GitHub Release
      if: startsWith(github.ref, 'refs/tags/v')
      uses: softprops/action-gh-release@v2
      with:
        name: Release ${{ env.RELEASE_VERSION }}
        draft: false
        prerelease: false
        body: |
          ## Changes in version ${{ env.RELEASE_VERSION }}
          
          Published to Maven Central: https://central.sonatype.com/artifact/io.tileverse.pmtiles/tileverse-pmtiles-parent/${{ env.RELEASE_VERSION }}